### ISSUE TITLE
Update input project name format

### ISSUE THREAD

**Issue by doo5643** [AItoAir/tinyboom-linux-cli#4]
Please update CLI args as simpler structure, so it accepts single project number.
From `node aitoair-cli --project P000000003 --api-key 38b9647b-f081-44a0-850a-3bb6b7056f2a` -> 
To `node aitoair-cli --project 3 --api-key 38b9647b-f081-44a0-850a-3bb6b7056f2a`

**Comment by rowellpica** [comment]
Fixed in 8d3eee428e0421ec2ea71327918b754575a26b0b

**Comment by rowellpica** [comment]
Applied in staging
